version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chm-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8dgfbzkmewxn"
s3_prefix = "chm-backend"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
